from datetime import datetime
from app.schemas.incident import ReportContent, RootCause, Recommendation
from typing import List

class ReportGeneratorAgent:
    def generate(self, incident_desc: str, root_cause: RootCause, recommendations: List[Recommendation]) -> ReportContent:
        summary_md = f"# Incident Postmortem: {incident_desc}\n\n"
        summary_md += f"**Date**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        summary_md += f"**Status**: Analysis Completed\n\n"
        
        summary_md += "## Root Cause Analysis\n"
        summary_md += f"**Probable Cause**: {root_cause.cause}\n"
        summary_md += f"**Confidence**: {root_cause.confidence_score * 100}%\n"
        summary_md += f"**Reasoning**: {root_cause.reasoning}\n\n"
        
        summary_md += "## Recommendations (Read-Only)\n"
        for i, rec in enumerate(recommendations, 1):
            summary_md += f"{i}. **{rec.action}**: {rec.description}\n"
            
        summary_md += "\n> [!NOTE]\n> This report was generated by AI Operations Copilot. Please verify all findings manually."

        return ReportContent(
            summary=summary_md,
            root_cause=root_cause,
            recommendations=recommendations,
            generated_at=datetime.now()
        )
